- apps/client/app.vue
- apps/client/components/CourseItemCard/index.vue
- apps/client/components/Footer/index.vue
- apps/client/components/Navbar/index.vue
- apps/client/layouts/default.vue
- apps/client/pages/Main/[id].vue
- apps/client/pages/index.vue
layout  file place in `app/client/layouts`, `layouts/default.vue` will be added in each page automat automatically.
homepage is wip now.
> feat: setup layout and home page 

- apps/client/components/Navbar/index.vue
- apps/client/layouts/default.vue
- apps/client/pages/index.vue
- apps/client/tailwind.config.js
> feat: new homepage

- apps/client/api/http.ts
- apps/client/components/Navbar.vue
> fix: http status code

- apps/client/nuxt.config.ts
> feat: add page icon and title

- apps/client/assets/css/globals.css
- apps/client/components/Navbar.vue
like this: https://unocss.dev/interactive/
> feat: add an animation when toggle dark mode

- apps/client/components/Loading.vue
> feat: add loading

- apps/client/app.vue
- apps/client/components/Navbar.vue
- apps/client/composables/darkMode.ts
refactor: refactor darkmode logic and cache current mode
fix: naive-ui dark mode support
> fix: naive-ui dark mode support

- apps/api/src/tool/tool.service.ts
> fix: Daily sentence api return the same sentence everyday

- scripts/course/courses/02.json
1. 订正`02.json` 中第112/165 `告诉我`中文文案
> docs: Refactor translation in 02.json

- README.md
- README.zh-CN.md
> doc: add solution of permission denied for docker to readme.md

- apps/client/app.vue
> fix: hide FeHelper json dom

- apps/client/composables/main/game.ts
- apps/client/middleware/auth.ts
1. 修复切换课程时 gameMode 值未重置为 question 导致会在进入页面后显示答案问题 #87
> fix: GameMode not reset error when switching courses

- apps/client/package.json
- apps/client/store/course.ts
- apps/client/store/user.ts
- pnpm-lock.yaml
参考官方文档[pinia在nuxt中的使用](https://pinia.vuejs.org/zh/ssr/nuxt.html)，以及[vitesse-nuxt3](https://github.com/antfu/vitesse-nuxt3)模版，使用@pinia/nuxt模块，并且defineStore已经是自动导出，无需再安装pinia手动引入。
解决 pinia store 的类型错误问题 https://github.com/cuixueshe/earthworm/issues/73
> fix: fix bug #73

- apps/client/pages/Auth/Login.vue
- apps/client/pages/Auth/SignUp.vue
之前：在登录/注册页面只能通过鼠标点击 Log in 或者 Sign in 操作
新增：能通过回车来提交信息
> add enter-submit-form

- apps/client/components/Navbar.vue
- apps/client/components/main/Tips.vue
- apps/client/components/user/Home.vue
- apps/client/components/user/Menu.vue
- apps/client/components/user/Setting.vue
- apps/client/composables/user/setting.ts
- apps/client/pages/User/Info.vue
- apps/client/store/user.ts
关联到 #64 
新增userInfo 页面, 两栏布局, 左侧菜单栏可后续拓展
菜单[设置]中, 新增自定义快捷键功能
> feat: custom shortcut keys

- apps/client/components/main/MessageBox.vue
> click outside the reset tips dialog to close it

- scripts/course/courses/05.5.json
> fix: course5.5 statement incorrect

- apps/client/components/main/StudyVideoLink.vue
- apps/client/components/main/Tool.vue
> feat: add study video icon and link

- apps/client/components/Navbar.vue
> fix(Navbar): update svg in dark mode

- apps/client/components/main/Answer.vue
- apps/client/components/user/Setting.vue
- apps/client/composables/user/sound.ts
- apps/client/composables/user/tests/sound.spec.ts
- apps/client/package.json
> feat: auto play sound switch

- apps/client/composables/user/setting.ts
> fix(setting): avoid entering null values

- apps/client/composables/user/setting.ts
> fix(setting): update cmd key display in the shortcut settings

- apps/client/components/main/MessageBox.vue
- apps/client/pages/index.vue
> feat: add mobile tips

- scripts/course/courses/15.5.json
> fix: update course 15.5-28

- apps/client/components/main/Question.vue
- apps/client/store/course.ts
- apps/client/store/tests/course.spec.ts
> style: variable question word width

- apps/client/pages/index.vue
> chore: perfect use introduction

- package.json
- pnpm-lock.yaml
在 push 代码之前做以下检测
1.测试是否全部通过
2. eslint代码格式化
3. 进行打包操作，确认是否存在 build 问题。 [（请佬们看看是否有问题）]
> chore: execute lint before push 

- apps/client/composables/main/summary.ts
- apps/client/composables/main/tests/summary.spec.ts
> Unit test of summary modal

- apps/client/components/main/Tips.vue
- apps/client/components/user/Setting.vue
- apps/client/composables/user/shortcutKey.ts
- apps/client/composables/user/tests/shortcutKey.spec.ts
添加自定义快捷键模块单元测试
期待大佬完善一下剩余测试，学习学习
> test: add shortcut key unit test

- apps/client/components/main/Summary.vue
- apps/client/composables/main/englishSound/index.ts
增加朗读每日一句，弹出弹窗时自动朗读，也可点击按钮/快捷键朗读
> readOneSentencePerDayAloud

- apps/client/components/main/Question.vue
> inputWidth function

- apps/client/components/main/Question.vue
- apps/client/components/user/Setting.vue
- apps/client/composables/user/submitKey.ts
- apps/client/composables/user/tests/submitKey.spec.ts
> feat: submit with space

- scripts/course/courses/11.json
> fix: update the soundmark of course

- scripts/course/courses/20.5.json
- scripts/course/courses/25.5.json
- scripts/course/courses/27.json
- scripts/course/courses/31.json
- scripts/course/courses/38.json
> fix soundmark of some courses

- scripts/course/courses/32.json
> fix: fix answers to lesson 32

- apps/client/composables/user/shortcutKey.ts
> fix: custom shortcuts not working close #197

- apps/client/composables/main/question.ts
- apps/client/composables/main/tests/question.spec.ts
修复 issue 问题 #202 
> 空格提交前提条件
- Input（编辑模式）下当前编辑单词为最后一个单词
我的补充：
- 不处于 Fix（修复模式）
- Fix_Input（修复编辑模式）下当前编辑的单词为最后一个错误单词
> fix: last wrong word can be submitted using space close #202

- apps/client/assets/css/globals.css
- apps/client/pages/index.vue
- 项目中使用的是 原生滚动条样式, 有点小丑, 小小的修饰一下
- 修复 index 页面的滚动条不在card盒子里面情况
> style:optimize global scrollbar style

- apps/client/pages/index.vue
> style: added homepage quick start introduction

- apps/client/components/user/CalendarGraph.vue
- apps/client/composables/user/calendarGraph.ts
- apps/client/composables/user/tests/calendarGraph.spec.ts
> fix: update tooltip text

- apps/client/pages/index.vue
> chore: add learning principle of earthworm

- apps/client/composables/main/question.ts
> fix: clear value on reset

- apps/client/components/main/Question.vue
> 增加单引号宽度例如：can't don't

- apps/client/pages/index.vue
1. 首页添加公告组件，可用于以后更新版本通知。
2. 样式展示：
> feat: add announcement module to homepage

- apps/client/components/courses/CourseCard.vue
https://github.com/cuixueshe/earthworm/issues/253
> feat: automatically locates the active course location

- .github/ISSUE_TEMPLATE/feature_request.yml
新增一个文本区域表单字段，允许用户提供关于特性请求的任何额外信息或上下文
> feat: add template context

- apps/client/app.vue
- apps/client/components/HttpErrorProvider.vue
- apps/client/components/Navbar.vue
- apps/client/components/main/Message/Message.ts
- apps/client/components/main/Message/message.vue
- apps/client/pages/Auth/Login.vue
- apps/client/pages/Auth/SignUp.vue
做的一些工作
1.初步封装了全局消息通知message组件，并暴露一些方法，代替了native-ui中的message组件
2.在之前使用native-ui的message组件的地方，全部替换成自己封装的message组件
3.为登陆注册增加消息提示
> feat: add message

- packages/xingrong-courses/data/courses/16.json
- packages/xingrong-courses/data/courses/43.json
> fix: some chinese content

- packages/db/drizzle.config.ts
修复执行`db:init`时报`No schema files found for path config ['../../libs/shared/src/schema/*']`错误的问题，related #336
> fix: db init error

- apps/client/utils/keyboardShortcuts.ts
- apps/client/utils/tests/keyboardShortcuts.spec.ts
> fix: global shortcut keys are invalid

- apps/client/composables/main/shareImage/imageTemplates/tpl_2.ts
分享页第 2 个模板，增加一层0.2透明度的黑色背景，防止背景图大量白色区域导致看不见白色字体
避免类似这种效果
> style: add a background color with 0.2 transparency to tpl_2 file

- apps/client/pages/Auth/Login.vue
- apps/client/pages/Auth/SignUp.vue
close #349 
Correct message of login/register
> fix: correct message of login/register

- apps/client/components/main/Question/Question.vue
- apps/client/composables/main/question.ts
- apps/client/tailwind.config.js
> feat: improve incorrect effect

- packages/xingrong-courses/data/courses/35.json
> fix: update lesson 35 data

- packages/db/drizzle/0001_colossal_lilandra.sql
- packages/db/drizzle/meta/0001_snapshot.json
- packages/db/drizzle/meta/_journal.json
> chore: Miss Database Schema Migration Log

- apps/client/composables/darkMode.ts
refactor setDarkMode function by a batter way
> refactor(useDarkMode): refactor setDarkMode fn

- apps/client/app.vue
- apps/client/package.json
- pnpm-lock.yaml
- 移除 package.json 依赖
- 移除 app.vue 主题相关
> chore: remove naive-ui dependencies

- apps/client/components/main/Share.vue
打卡弹窗在mac上存在样式展示不全的问题，
修改样式结构解决按钮展示不全的问题
> feat: change share dialog style to fix style error

- apps/client/components/main/Contents/Contents.vue
> fix: add dropdown background

- apps/client/components/main/Contents/Contents.vue
- apps/client/components/main/Question/Question.vue
> feat: show tips when 3 times wrong

- apps/client/components/user/Setting.vue
- apps/client/composables/user/shortcutKey.ts
- apps/client/composables/user/tests/shortcutKey.spec.ts
Dear teams:
I have modified some files of contents, below sections for your reference: 
1. Added typescript type to improve the method or the variable strong.
2. Deleted some cases for the test file.
if any problems, please contact me,  thanks~
> Fix user defined shortcut key

- apps/client/components/main/Contents/Contents.vue
- apps/client/components/main/Contents/useContents.ts
#448
改动：加宽，点击隐藏content，单行显示超出部分有省略号，增加tooltip
> fix: optimize statement directory list style

- apps/client/components/main/Tips.vue
- apps/client/components/user/Setting.vue
- apps/client/composables/user/shortcutKey.ts
- apps/client/composables/user/tests/shortcutKey.spec.ts
- apps/client/utils/keyboardShortcuts.ts
- apps/client/utils/tests/keyboardShortcuts.spec.ts
> fix: optimize style of shortcut keys

- apps/client/composables/darkMode.ts
将 theme 模式信息由 sessionStorage 改存到 localStorage 
related to #465
> fix: save the theme mode to localStorage

- apps/client/components/rank/RankingList.vue
> style: update border color of rank item in dark mode

- apps/client/pages/index.vue
> perf: convert to Chinese

- apps/client/components/main/Share.vue
- apps/client/composables/main/shareImage/imageTemplates/tpl_1.ts
- apps/client/composables/main/shareImage/imageTemplates/tpl_2.ts
- apps/client/composables/main/shareImage/share.ts
- apps/client/utils/date.ts
- apps/client/utils/tests/date.spec.ts
> feat(share): add course time and number to share image

- apps/client/components/Navbar.vue
> fix: navbar click hide bug

- apps/client/layouts/default.vue
> fix: game page width bug

- apps/client/composables/rank/rankingList.ts
- apps/client/composables/rank/tests/rankingList.spec.ts
Dear Team,
It's a unit test PR for the ranking file with three sections updated:
1. Moved the variable 'rankModal' to the top of  the store
2. Moved the variable 'rankingCache' out of the cacheRanking method 
3. Added unit test
if any problems, please feel free to contact me, thanks😁~
> test: add unit test for rankingList

- apps/client/components/Navbar.vue
- apps/client/layouts/default.vue
- apps/client/pages/index.vue
改动如下：
- 在窄屏幕下缩小padding
- 在小于500px的屏幕去除logo和 减少usrname的最大长度
- bug修复：在未登录的时候去除用户名部分的dom
- 让中心部分始终保持居中
效果图对比稍后附上
> feat: add home page responsive style

- apps/api/src/auth/auth.controller.ts
- apps/api/src/course-history/course-history.controller.ts
- apps/api/src/course/course.controller.ts
- apps/api/src/game/game.controller.ts
- apps/api/src/main.ts
- apps/api/src/rank/rank.controller.ts
- apps/api/src/tool/tool.controller.ts
- apps/api/src/user-progress/user-progress.controller.ts
- apps/api/src/user/model/user.dto.ts
- apps/api/src/user/user.controller.ts
功能描述：
给项目中的api具体描述添加到swagger文档中。
可以通过 [:::]/swagger 访问接口文档。
> feat: add swagger api docs

- apps/client/components/main/Tool.vue
> feat: add style in Tool-progress-bar

- apps/client/components/main/Answer.vue
1. 按钮显示中文文案
2. 播放喇叭增加 hover 效果
修改前：
修改后：
> fix(Answer): optimize button styling and text desc

- apps/client/pages/Auth/CountryPhoneInput.vue
- apps/client/pages/Auth/FormInput.vue
1、修复了原先通用组件中和phone组件高度不一致问题
2、处理svg样式时候，顺便处理了密码显示开闭眼的样式
> fix: fix input style and add isPasswordVisible

- apps/client/composables/user/pronunciation.ts
https://github.com/cuixueshe/earthworm/issues/586
> fix: set correct pronunciation API type

- apps/client/components/home/Banner.vue
> feat(homepage): add the star button in homepage

- apps/client/components/main/MessageBox/MessageBox.vue
> fix: update the button name for messageBox 

- apps/api/src/rank/rank.service.ts
- apps/client/components/Navbar.vue
- apps/client/components/main/Share.vue
- apps/client/store/user.ts
> fix: use email address with empty username

- packages/xingrong-courses/data/courses/20.json
lesson 20: updated prompt word
> fix: updated prompt word

- .github/workflows/ci.yaml
close #598 
see https://github.com/baboon-king/draft-pr-dont-run-action/pulls
> chore: draft PR not run CI

- apps/client/components/home/Questions.vue
update punctuation mark on homepage
> chore: typo

- apps/client/components/mode/chineseToEnglish/Question.vue
- apps/client/components/user/Setting.vue
- apps/client/composables/user/sound.ts
- apps/client/composables/user/tests/sound.spec.ts
close #609 
答题页面自动播放声音 
设置也添加控制按钮
> feat :  The answer page automatically plays the sound and adds settings

- apps/client/components/user/Setting.vue
- apps/client/store/user.ts
closed #604 
目前已经做好了 update 昵称功能，是这样的。
一个小小的优化点，增加一个更新按钮，因为并不是所有用户知道可以回车修改昵称。这样对用户交互更友好
> feat: add nickname update button

- packages/xingrong-courses/data/courses/50.json
> fix: the fifth course content error

- packages/xingrong-courses/data/courses/02.json
Hi Team,
The below sentence fixed: 
I am 18 to I am eighteen.
> docs: fixed some sentence in the course02.json file

- apps/client/components/main/Game.vue
- apps/client/composables/main/game.ts
- apps/client/utils/detectDevice.ts
close #506 
在ipad未横屏，或者只是手机端使用的时候弹窗提示
”横屏使用效果更佳哦~“ 或者 ”目前暂时不支持移动设备哦，请关注后续更新“
> feat: add device tip

- apps/client/components/main/Tool.vue
> feat: add tips for the reset button of game

- apps/client/components/DropMenu.vue
- apps/client/components/Footer.vue
- apps/client/components/Home/CalendarGraph.vue
- apps/client/components/Home/RecentCoursePack.vue
- apps/client/components/Home/index.vue
- apps/client/components/Landing/index.vue
- apps/client/components/Navbar.vue
- apps/client/layouts/default.vue
- apps/client/pages/User/Setting.vue
- apps/client/pages/index.vue
- apps/client/tailwind.config.js
> refactor: adjust course packs page style

- apps/client/components/Home/CalendarGraph.vue
- apps/client/components/Home/RecentCoursePack.vue
- apps/client/components/Home/index.vue
> feat: opt home style

- apps/client/components/Home/RecentCoursePack.vue
- apps/client/components/Home/index.vue
> fix: home style bug

- apps/client/components/Home/index.vue
- apps/client/pages/course-pack/[id].vue
- apps/client/pages/course-pack/index.vue
> fix: mulit page scroll bug

- apps/client/components/main/Message/Message.vue
> fix: global tips level bug

- README.md
- README.zh-CN.md
> docs: add star history charts

- packages/docs/contribution/index.md
将文档 贡献代码/如何贡献代码? 目录下的最后一行"贡献你，你已成功提交一个PR"错别字修正为"恭喜你，你已成功提交一个PR"
> fix: correct typos in document

- apps/client/pages/User/Setting.vue
user setting page, in mobile mode,
container classes min-w-max make page exceeding their width
> fix: user setting page, in mobile mode, page exceeding their width

- apps/client/components/main/Tool.vue
> fix: pause game can open print web page
