apps/client/components/main/Question.vue
1. 限制只能键入一个空格，防止仅有一个单词或者最后一个单词时输入一个以上空格后继续输入，前端不正常显示的问题。
2. 在仅有一个单词或光标在最后一个单词的后面有一个空格时，按一次退格键即可正常删除最后一个字母，而不是两次
related to #93
=> fix(Question): prevent multiple spaces from being entered #93

apps/client/components/main/Question.vue
问题描述：
用户在最后一个输入框输入内容时，单词输入完按下空格没被阻止，导致会有多余的字符
修改：
新增最后一个单词后的空格阻止逻辑： 当用户完成最后一个单词的输入并尝试在其后添加空格时，进行阻止
=> fix: Prevents adding Spaces after the last word

apps/client/package.json, apps/client/pages/Auth/FormInput.vue, apps/client/pages/Auth/Login.vue, apps/client/pages/Auth/SignUp.vue, apps/client/store/tests/user.spec.ts, apps/client/store/user.ts
本次修改：重构登录和注册表单移除原先naive-ui，使用Tailwind和Vee-Validate
描述：
本次PR主要完成了以下工作：
移除了登录注册页面中对naive-ui的依赖
重写了登录和注册表单的样式，使用Tailwind CSS替代原先的样式
更新了表单验证逻辑，采用vee-validate替代naive-ui表单验证
=> refactor: Login and SignUp remove-naive-ui-use-tailwind-vee-validate

drizzle.config.ts
drizzle-kit 连接库时，读取不到 `.env` 配置中的变量，导致 `db:init` 执行失败
=> fix: set the drizzle config path

scripts/course/courses/15.5.json
{
"chinese": "在卧室里睡觉",
"english": "to sleep in the bed room",
"soundmark": "/tə/ /slip/ /ɪn/ /ðə/ /'bɛdrum/"
},
原先是 bed room 两个格子 
修复后： bedroom 应为一个单词
=> fix: fix course 18 the ninety-first field is incorrect

scripts/course/courses/34.json
错误描述：
{
"chinese": "通过一个手头",
"english": "by a stone",
"soundmark": "/baɪ/ /ə/ /ston/"
},
chinese： 通过一个手头 错误 。
修正：
"chinese": "通过一个石头"
=> fix: fix course-34 statement is incorrect

scripts/course/courses/04.json
course-04错误描述以及修复：
1."english": "it doesn't have to",  to对应的下方音标“to"字段多余，进行删除
{
"chinese": "它不必",
"english": "it doesn't have to",
"soundmark": "/ɪt/ /ˈdʌznt/ /hæv/"
},
2."chinese": "它不必现在在床上睡觉", “现在”这个时态多余，进行删除
{
"chinese": "它不必现在在床上睡觉",
"english": "it doesn't have to sleep on the bed",
"soundmark": "/ɪt/ /ˈdʌznt/ /hæv/ /tə/ /slip/ /ɑn/ /ðə/ /bɛd/"
}
=> fix: fix course issue, closes #118

scripts/course/courses/20.json
错误描述：
chinese：我的包  -> 应为 ： 我的书包。 第一反应是my bag
{
"chinese": "我的包",
"english": "my school bag",
"soundmark": "/maɪ/ /skul/ /bæɡ/"
},
修正后： "chinese": "我的书包"
=> fix: fix course-20 statement is incorrect

scripts/course/courses/11.json, scripts/course/courses/12.json, scripts/course/courses/13.json, scripts/course/courses/14.json, scripts/course/courses/15.5.json, scripts/course/courses/16.json, scripts/course/courses/17.json, scripts/course/courses/18.json, scripts/course/courses/19.json, scripts/course/courses/20.5.json, scripts/course/courses/21.json, scripts/course/courses/22.json, scripts/course/courses/23.json, scripts/course/courses/24.json, scripts/course/courses/26.json, scripts/course/courses/27.json, scripts/course/courses/29.json, scripts/course/courses/30.json, scripts/course/courses/32.json, scripts/course/courses/33.json, scripts/course/courses/38.json, scripts/course/courses/41.json, scripts/course/courses/42.json, scripts/course/courses/43.json, scripts/course/courses/45.json
=> fix: update courses soundmark

scripts/course/courses/30.json
=> fix: sentence error (30 lessons)

apps/client/components/main/MessageBox.vue, apps/client/pages/index.vue
As a keyboard user i noticed 2 problems in the home page:
1) After focusing on theme toggle button, if user presses tab (to focus to next element) the focus indicator disappears, leaving user not knowing where the focus is.
I added a style so the modal (where focus is moved to) is hidden from accessibility tree, and focus navigation works as expected, moving to button.
2) The button "Star us on Github" also has an issue, because it has a button inside anchor tag (which hurts a11y), one visual element now takes 2 focuses (one for anchor, and one for button), and one focus (button focus) doesn't do anything.
I removed button and merged its styles to anchor.
=> fix: a11y bugs in home page

scripts/course/courses/18.json
修改前：
{
        "chinese": "是",
        "english": "be(am) is",
        "soundmark": "/was/"
    },
    {
        "chinese": "是",
        "english": "be(is ) is",
        "soundmark": "/was/"
    },
    {
        "chinese": "是",
        "english": "be(are) is",
        "soundmark": "/were/"
    },
修改后：
{
        "chinese": "是(单数，和我连用)",
        "english": "be am",
        "soundmark": "/bi/ /əm/"
    },
    {
        "chinese": "是(单数)",
        "english": "be is",
        "soundmark": "/bi/ /ɪz/"
    },
    {
        "chinese": "是(单数)(过去)",
        "english": "be was",
        "soundmark": "/bi/ /was/"
    },
    {
        "chinese": "是(复数)",
        "english": "be are",
        "soundmark": "/bi/ /ɚ/"
    },
    {
        "chinese": "是(复数)(过去)",
        "english": "be were",
        …
=> fix: update lesson 18 data

apps/client/composables/user/tests/shortcutKey.spec.ts
This is a unit test file for the shortcutKey.ts file.
There are four parts covered in the file.
1. Initial shortcut keys 
2. Open or close modal
3. Store the custom shortcut key in local storage, there are two situations involved: 
- store a single key 
- store key combination
5. Tips
For more details, please view the file.
if have any problems, please contact me I will reply as soon as possible.
Thanks.
=> feat: add shortcut key unit test

apps/client/nuxt.config.ts, apps/client/package.json, pnpm-lock.yaml
[Naive UI module for Nuxt 3](https://github.com/becem-gharbi/nuxt-naiveui)
看了下这个 `@bg-dev/nuxt-naiveui` 是 nuxt 的 naiveui 组件，但是项目中并没使用到，前端启动时会报 warning，所以就将这部分依赖去掉好了，related to https://github.com/cuixueshe/earthworm/issues/179
=> chore: remove nuxt-naiveui dependencies

apps/client/components/main/Tips.vue, apps/client/components/user/Setting.vue, apps/client/composables/user/shortcutKey.ts
#412 
新增跳过当前问题按钮,以及快捷键crtl+,
https://github.com/cuixueshe/earthworm/assets/75771172/0f524777-71b0-4f2d-9b2c-3944232c5c15
=> feat: add next button

apps/client/components/main/Game.vue, apps/client/components/main/PrevAndNextBtn.vue, apps/client/components/main/Tips.vue
related to issue #430 
- 修改 上一题/下一题 按钮样式
- 为 上一题/下一题 按钮添加 tooltip
- 当题目为第一题时，隐藏上一题按钮；当题目为第最后一题时，隐藏下一题按钮
- 删除原上一题/下一题 按钮
=> fix: change the style of the prev/next question btn on the game page

apps/client/components/user/Setting.vue, apps/client/composables/user/shortcutKey.ts, apps/client/composables/user/tests/shortcutKey.spec.ts
=> fix: verify whether shortcut keys are duplicated

apps/client/components/main/AnswerTip.vue, apps/client/components/main/Question/Question.vue
#445 
现在AnswerTip可以被正确的关闭，并且关闭按钮常显
=> fix: AnswerTip close correctly & always show close icon

apps/client/components/main/Answer.vue, apps/client/components/main/AnswerTip.vue, apps/client/components/main/Contents/Contents.vue, apps/client/components/main/Game.vue, apps/client/components/main/PrevAndNextBtn.vue, apps/client/components/main/Question/Question.vue, apps/client/components/main/Tips.vue
> 关于适配，做了一些微调
1. 游戏页面：底部快捷键区域平铺 ✅
2. 游戏页面：将切换上/下题目组件移动到 Tips 页面中 ✅
3. 答题页面：去除绝对定位 + 调整边距 ✅
4. 答题页面：将中文调整到上面，英文输入部分放下面 ✅
5. 答题页面：调整字体大小与高度 ✅
6. 答案页面：增加中文补充，方便与英文核对含义 ✅
7. 答案预览页面：位置往上一点点 ✅
8. 调整剩余细节（与其他元素的层级显示）✅
**小屏预览 10:5**
**iPad mini 10:7**
**正常 PC 用户 1920x1080**
**答案预览面板**
**答案页面**
=> fix: adjust game page display

apps/client/components/main/PrevAndNextBtn.vue
=> feat: add click feedback to the previous and next question buttons

packages/xingrong-courses/src/courses.ts
修复执行 `pnpm db:upload` 时报错
> Cannot delete or update a parent row: a foreign key constraint fails (`earthworm_nest`.`statements`, CONSTRAINT `statements_course_id_courses_id_fk` FOREIGN KEY (`course_id`) REFERENCES `courses` (`id`))
原因是 `courses` 表 与 `statements` 表之间存在外键约束，删除主表 `courses` 的同时还要删除外键表 `statements`
=> fix: db upload error

packages/xingrong-courses/data/courses/39.json, packages/xingrong-courses/data/courses/42.json, packages/xingrong-courses/data/courses/48.json, packages/xingrong-courses/data/courses/49.json, packages/xingrong-courses/data/courses/50.json, packages/xingrong-courses/data/courses/51.json
修改了部分课程中的中文语义，将 `(ed形式)` 修改为 `(过去分词)` 。
=> 中文语义的问题：误把动词过去分词形式写成“ed形式”

apps/client/components/Navbar.vue, apps/client/layouts/default.vue, apps/client/pages/index.vue
1. 修复新首页顶部黑色区域问题；
2. 修复开始按钮适配 2K 屏幕宽度问题；
3. 修复新页面game页面滚动问题；
=> fix(client): home page style question

apps/client/components/Navbar.vue, apps/client/components/user/Menu.vue, apps/client/pages/User/Info.vue
1. 修复新首页遗留跳转 bug
- Desc: 
- 	之前 Account Info 和 Setting 都跳转到 userInfo 页面显示的 Home 组件
=> fix(client): home router skip bug

apps/client/pages/Auth/FormInput.vue, apps/client/pages/Auth/hooks/useLoginForm.ts
1. 密码输入框添加快捷查看密码按钮
2. 密码输入框添加校验规则：不能输入中文
=> feat: add look password button

apps/client/components/Navbar.vue
1. 修复如下bug
2. 限制字符超过超过10个字，显示....
src="https://github.com/cuixueshe/earthworm/assets/88535417/6b515845-4b05-400a-ad07-2bc6d8ef0dbf">
=> fix: username bug

apps/client/components/main/AnswerTip.vue
修复听写模式下答案提示弹窗位置偏移问题。
close #525
=> fix(client): fixed the postion of answer tip in diction mode (close #525)

apps/client/components/main/Contents/Contents.vue
修复显示答案通过目录跳转还会继续下一题答案的问题
修复前
修复后
=> fix: show question page before switching statements

apps/client/components/Navbar.vue, apps/client/components/main/StudyVideoLink.vue
=> fix: game tips occlusion bug

apps/client/components/common/backTop.vue
建议采用opacity，因为有些屏幕下，这个transform的200%可能不准确导致
#548
=> style: backTop btn hover  transform change opacity

apps/client/components/Navbar.vue
navbar长度不够长，在移动端高斯模糊两侧出现缺口，不够美观
以前
现在
=> fix: make navbar long enough

apps/client/components/common/Divider.vue, apps/client/components/home/Questions.vue
优化首页样式
常见问题解答区域
1. border颜色优化(适配深色模式)
2. 边距优化(视觉不居中)
优化前
优化后
=> style: Optimize homepage styling

apps/client/pages/index.vue
修复首页点击[开启Earthworm]的时候loading未等待资源加载完成提前结束
修复前
修复后
=> fix(loading): Correct loading display on homepage redirection

apps/client/components/Navbar.vue
- 昨晚拉取了最新代码，在本地运行后，首页登录按钮错误问题：
- 修复前：
- 修复后：
=> fix(client): home login btn style bug

apps/client/composables/main/shareImage/imageTemplates/tpl_2.ts
-	修复第二张海报图片qrcode变形问题（目前大多数用户都使用第二张海报打卡）
之前:
之后：
=> fix: poster qrcode variation bug

.vscode/extensions.json, apps/client/package.json, apps/client/tailwind.config.js, pnpm-lock.yaml
**目前在项目中并为处理任何 SVG 图标替换，待方案确认集成后，期待小伙伴们的 PR** 😊
在这里 issue 中讨论了下方案：[关于项目中的 SVG 标签影响代码可读性问题](https://github.com/cuixueshe/earthworm/issues/566)
- [Iconify for Tailwind CSS](https://iconify.design/docs/usage/css/tailwind/) - 教你怎么在 tailwind 里面用 iconify
- [Innei/Shiro](https://github.com/Innei/Shiro) - 内神的项目已经很全面了，也是 tailwind + iconify，参考 icon 方案
- [Icon Sets - Iconify](https://icon-sets.iconify.design/?keyword=twemoji) - iconify 官方的图标检索平台
- [Icônes](https://icones.js.org/) - 托尼写的图标检索平台，体验下来，比官方的好用多了
- **优点**：智能提示很舒服，写法上更偏向 unocss 的使用
- **缺点**：带来的问题就是开销更大，因为它是直接把全部的 `icon` 生成在 `components` 里, 然后再交给 `Tailwind CSS` 从里面进行挑选再输出到我们的 `css` 文件中的，不过问题不大
```bash
pnpm add -D @egoist/tailwindcss-icons
pnpm add -D @iconify-json/ph
```
```js
const {
iconsPlugin,
getIconCollections,
} = …
```
=> chore: integration iconify for TailwindCSS

apps/client/components/rank/RankingItem.vue
=> fix: rank empty username bug

apps/client/components/Landing/Banner.vue
暂时解决问题，应该和z-index的层级关系有关，可以考虑后期重构样式的部分到tailwindCSS
=> fix: misaligned style of 'Start Earthworm' button

apps/client/components/Home/RecentCoursePack.vue, apps/client/components/Home/index.vue, apps/client/components/Navbar.vue, apps/client/pages/User/Setting.vue, apps/client/tailwind.config.js
- 对齐右侧按钮（顶部导航栏 / 更多课程包 / 2024） ✅
- 将 Navbar 最后一个 icon 向右移动一点
- 保证主体内容区域不变
- 填充头像圆角切割的空隙 ✅
- 去掉课程包的边框（不好看）✅
- 重写卡片布局样式（不用 daisyUI）✅
- 缩小整体卡片 ✅
- 添加图片默认底色 ✅
- 设置卡片固定高度
- 标题单行省略号 ✅
- 描述双行省略号 ✅
- 设置描述区域最低高度 ✅
- 响应式适配 ✅
- 响应式动画过渡 ✅
- 增加鼠标悬停缩放动画 ✅
- 调整卡片内按钮颜色（不协调）✅
- 调整标题、描述字体大小以及颜色暗黑主题适配（边框和背景）✅
> 之前
> 现在
> 暗黑主题显示
=> style: optimize home page layout

apps/client/components/DropMenu.vue, apps/client/components/main/StudyVideoLink.vue
- 修复 DropMenu 下拉层级问题 
#670 
- 之前：
- 现在：
=> fix: dropmenu index bug

apps/client/assets/css/globals.css, apps/client/components/Home/CalendarGraph.vue, apps/client/components/Home/RecentCoursePack.vue, apps/client/components/Home/index.vue, apps/client/composables/user/calendarGraph.ts, apps/client/composables/user/tests/calendarGraph.spec.ts, apps/client/pages/User/Setting.vue
- 设置最低高度以及默认背景色（图片加载过程中占位显示）
- 不固定高度 + 宽度根据 grid 布局占满
- 设置图片根据比例显示填充（超出部分裁剪隐藏）
- 响应式优化：在缩放时保持内部大小不变，外层盒子出现横向滚动条，而不是固定占位大小
- 更改为中文提示（月份 / 星期 / 悬停提示文本）
- 年份从底部左侧移动到右侧（小屏时隐藏保证打卡图的显示完整性）
- 设置默认滚动条高度
> 之前
> 现在
> 滚动条显示
=> style: optimize calendar graph responsive layout

package.json, pnpm-lock.yaml, scripts/verify-commit.ts
1. 引用picocolors包，虽然在vite库中有关于该包的引用，但是最好还是把该引用放到自己的项目中更安全，且lint检测会报红。
3. 删除无用的console.log. 使用 模版字符串``可以实现换行效果，没必要为了换行而专门使用一个log.
=> chore: add picocolors modules & delete useless log

apps/client/components/Home/index.vue, apps/client/components/Navbar.vue
#698 
使用 1x1 像素的透明 GIF 图片，消除头像图片加载失败时的边框
=> fix: optimize user avatar loading or error display

apps/client/components/Home/RecentCoursePack.vue
课程首页——课程包列表加载前后，打卡图在页面的位置出现轻微抖动
课程包列表 `loading` 状态下的最小高度 `min-h-80` 无法包含课程包卡片加载后的高度
增加课程包的最小高度到 `min-h-[350px]`
保证加载中和加载后显示的高度一致，避免 **高度闪烁** 问题
=> style: fix page element shake after loading

apps/client/nuxt.config.ts
- Fix website favicon path error
-	Before：
-	Now:
=> fix(client): website favicon path error

apps/client/components/courses/CoursePackCard.vue
在小屏幕下card的间距出现无法适配的情况（大概在768px-933px）
做了一个微小的工作：
1、card 的宽度 从固定宽度width改为 最大max-width.
使得卡片可以在屏幕大小在768px-933px之间可以自动缩小卡片保持间距
修改后：
=> fix: card-between-without-gap

apps/client/pages/course-pack/index.vue
I centered the cards' horizontal position by adding tailwind css class.
this is related with issue #716. 
What it looks like now
=> fix: center cards in course-pack page under narrow screen size 

apps/client/components/Home/RecentCoursePack.vue
-	问题：
- 当新用户进入到首页时，最近课程区域空白，对于小白用户不是很友好。
-	修改点：
- 增加`友好提示` 和 `快捷学习入口`。
- 快捷学习入口 跳转 课程包 页面
-	之前：
-	现在：
=> feat: add empty recent course tips

apps/client/pages/course-pack/index.vue, apps/client/tailwind.config.js
- 描述：
- 	多课程包页面滚动样式优化
- 修改点：
1. 多课程包页面修改为局部滚动。
2. 修复之前 `scrollbar-hide` 类未正确定义使用问题。
- 之前：
- 现在：
=> fix: course pack scroll bug

apps/client/components/courses/CourseCard.vue
For better user experience, we should add pointer to the area where can be clicked by user,
=> chore: add pointer for course-card

apps/client/components/Navbar.vue
1. set a href default value
2. add type to `HEADER_OPTIONS`
It's pointless!There is no default value set.
```ts
optItem.target ?? optItem.target
// https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/a#target
=> optItem.target ?? '_self'
```
`optItem.target ?? '_self'` is equivalent to `optItem.target ? optItem.target : '_self'`
=> fix: set navbar a default value
